name: Flask CI/CD

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # The CI job
  build:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests (optional if you have tests)
      - name: Run tests
        run: |
          # Add your test command here, for example using pytest
          pytest

      # Step 5: Start the Flask app (optional)
      # This is just for testing if the app runs, it may not be needed in CI if no tests
      - name: Run Flask app
        run: |
          FLASK_APP=app.py flask run &
        continue-on-error: true  # This will not stop the job if Flask fails (since it's just a test)
