name: Flask CI/CD

# Trigger the workflow on push or pull request to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu runner

    steps:
      - uses: actions/checkout@v2  # Checkout the repository
      - uses: actions/setup-python@v2  # Set up Python environment
      - run: pip install -r requirements.txt  # Install dependencies
      - run: python -m unittest discover -s .  # Run tests using unittest (search for test*.py)
      - run: python app.py  # Run your Flask app (optional if not required for testing)
